name: Checksum
on:
  workflow_dispatch:
    inputs:
      file_url:
        description: File URL
        required: true

jobs:
  checksum:
    runs-on: ubuntu-latest
    env:
      FILE_URL: ${{ inputs.file_url }}
    steps:
      - name: Download file
        run: 7z x "$(curl -LOJ -w "%{filename_effective}" "$FILE_URL")" || true

      - name: Checksum
        run: |
          7z h -r -scrcMD5
          7z h -r -scrcSHA256
