name: Download Source Code
on:
  workflow_dispatch:
    inputs:
      repository:
        description: Repository name with owner
        required: true
      ref:
        description: The branch, tag or SHA to checkout

jobs:
  download-source-code:
    runs-on: ubuntu-latest
    env:
      REPOSITORY: ${{ inputs.repository }}
      REF: ${{ inputs.ref }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          repository: ${{ env.REPOSITORY }}
          ref: ${{ env.REF }}

      - name: Download source code
        run: |
          rm -rf .git
          grep -rIL . | xargs -r truncate -s 0

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: output
          path: .
          include-hidden-files: true
