name: Strip APK Architecture
on:
  workflow_dispatch:
    inputs:
      apk_url:
        description: APK URL
        required: true

jobs:
  strip-apk-architecture:
    runs-on: ubuntu-latest
    env:
      APK_URL: ${{ inputs.apk_url }}
    steps:
      - name: Download APK
        run: curl -L -o app.apk "$APK_URL"

      - name: Strip APK architecture
        run: zip -d app.apk "lib/armeabi-v7a/*" "lib/x86/*" "lib/x86_64/*"

      - name: Checksum
        run: |
          cksum -a md5 app.apk
          cksum -a sha256 app.apk

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: output
          path: app.apk
