name: Strip APK Architecture
on:
  workflow_dispatch:
    inputs:
      apk_url:
        description: APK URL
        required: true

jobs:
  strip-apk-architecture:
    runs-on: ubuntu-latest
    env:
      APK_URL: ${{ inputs.apk_url }}
    steps:
      - name: Download APK
        run: |
          filename="$(curl -LOJ -w "%{filename_effective}" "$APK_URL")"
          printf "%s\n" "INPUT_FILENAME=$filename" >> "$GITHUB_ENV"

      - name: Strip APK architecture
        run: |
          zip -d "$INPUT_FILENAME" "lib/armeabi-v7a/*" "lib/x86/*" "lib/x86_64/*"

          7z h -scrcMD5 "$INPUT_FILENAME"
          7z h -scrcSHA256 "$INPUT_FILENAME"

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: output
          path: ${{ env.INPUT_FILENAME }}
